config/routes.rb
Rails.application.routes.draw do
  get 'user/user'
  root to: redirect('/gossipform')
  resources :gossipform
  resources :sessions, only: [:new, :create, :destroy]
  
  get '/team', to: 'team#team'
  get '/contact', to: 'contact#contact'

  get '/sessions', to: 'sessions#sessions'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user

    validates :title, length: { minimum: 3, maximum: 14 }
    validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :gossips

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def contact
  end
end

app/controllers/gossipform_controller.rb
class GossipformController < ApplicationController
    def create
        @gossip = Gossip.new('user_id' => User.all.sample.id,
                            'title' => params[:title],
                            'content' => params[:content]) # avec xxx qui sont les données obtenues à partir du formulaire
        if @gossip.save # essaie de sauvegarder en base @gossip
            redirect_to root_path(success: true)# si ça marche, il redirige vers la page d'index du site
        else
            render :new # sinon, il render la view new (qui est celle sur laquelle on est déjà)
        end
        # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
        # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
        # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
    end
    
    def index
        @gossips = Gossip.all # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def sessions
  end

  def new
  end

  def create
    user = User.find_by(email: email_dans_ton_params)
      if user && user.authenticate(password_dans_ton_params)
        session[:user_id] = user.id
      else
        flash.now[:danger] = 'Invalid email/password combination'
        render :new
      end
  end

  def destroy
    session.delete(:user_id)
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def team
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossipform_helper.rb
module GossipformHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
    end
    
    def log_in(user)
        session[:user_id] = user.id
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/contact/contact.html.erb
<h1>Nous contacter</h1>
<p>Pour contacter notre superbe équipe ? Rien de plus simple !</p>

<section class="contact-page">
  <div class="row text-center">
<p>Envoyez-nous un mail en cliquant ci-dessous :</p><a href="mailto:TheGossipProject@gmail.com">The Gossip Project</a>
</div>
</section>

app/views/gossipform/index.html.erb
<body data-turbo="false">
    <div class="container">
    <h1 class="display-4">Bienvenue ! <%= params[:id] %></h1>
    <p>Vous voici arrivé sur <b>the</b> site des potins. Un p'tit apperçu des doss' déjà connus :</p>
    <br /> <br />

    <div class="row">
        <% @gossips.each do |gossip| %>
    <div class="col-md-3">
      <div class="row">
        <div class="col-md-12">
          <div class="card mb-3 card-home">
            <div class="card-body mt-auto mb-auto">
              <h5 class="card-title"><%= gossip.title %></h5>
              <p class="card-text"><em><%= gossip.content %></em></p>
              <a href="potin/<%=gossip.id%>" class="btn btn-danger">Voir le potin</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
    </div>
 <%= yield %>

</body>

app/views/gossipform/new.html.erb
<h1>C'est ici pour lacher ton doss' !</h1>
<p>Fais toi plaisir, racontes-nous tes plus gros potins</p>
<br /> <br />

<main class= "container">
<%= form_tag url_for(action: 'create'), method: "post", authenticity_token: true do %>
    
  <div class="col">
    <%= label_tag 'Titre du potin' %>
    <br/>
    <%= text_field_tag 'title' %>
  </div>
      <br /> <br />

  <div class="col">
    <%= label_tag 'Contenu du potin' %>
    <%= text_area_tag 'content', '', class: 'form-control', id: 'floatingTextarea2', style: 'w-100px', placeholder: "Racontes ici.." %>
  </div> 
      <br /> <br />

  <div class="col">
    <%= submit_tag "Créer un potin", class: "btn btn-danger" %>
  </div>
<% end %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="application.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz4fnFO9gybBud7M4eQP3Gf2z6E2eP1w2FVI6G5pBt5eQ7mbrKj6ilB7Cz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-dxWUJ7E2w/tMxKlA6sVPtBzuJF6xEz0pH3NlRzU6G7z8LWUx6G5J5M5f5j5t6pD8" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <%= link_to "The Gossip Project", root_path, class:"nav-link" %>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" href="<%= team_path %>">Team</a>
        <a class="nav-link" href="<%= contact_path %>">Contact</a>
        <a class="nav-link" href="<%= new_gossipform_path %>">Gossip</a>
        <a class="nav-link" href="<%= sessions_path %>">Login</a>
      </div>
    </div>
  </div>
  <div class="btn-group">
  <%= button_tag 'Login', type: 'button', class: 'btn btn-danger dropdown-toggle', data: { bs_toggle: 'dropdown' }, aria: { expanded: 'false' } %>
  <ul class="dropdown-menu">
    <li><%= link_to 'Action', '#' %></li>
    <li><%= link_to 'Another action', '#' %></li>
    <li><%= link_to 'Something else here', '#' %></li>
    <li><hr class="dropdown-divider"></li>
    <li><%= link_to 'Separated link', '#' %></li>
  </ul>
</div>

</nav>
    <%= yield %>
  </header>
  </body>
</html>

app/views/team/team.html.erb
<h1>T'as reconnu l'équipe !</h1>
<p>Voici l'équipe de choc de The Gossip Project !</p>

<section class="page-group">
  <div class="row text-center">
    <div class="col-md-4">
    <%= image_tag("Hubert.png", alt: "Hubert", class:"img_logo_thirst") %>
    <h2>Hubert Bonisseur de la Bath</h2>
    <p class="text-muted">Alias OSS 117, aime se beurer la biscotte et les boules de Noël.</p>
    </div>
    <div class="col-md-4">
    <%= image_tag("Bill.png", alt: "Bill", class:"img_logo_second") %>
    <h2>Bill Trumendous</h2>
    <p class="text-muted">Ah ce bon vieux Bill ! Toujours le mot pour rire.</p>
    </div>
    <div class="col-md-4">
    <%= image_tag("Jack.png", alt: "Jack", class:"img_logo_third") %>
    <h2>Jack Jefferson</h2>
    <p class="text-muted">Il est mauvais Jack !</p>
    </div>
    </div>
    </div>
</div>
</section>

app/views/user/user.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <br>
      <h1> Création de ton compte</h1>

      <%= form_for @user do |f| %>
        <div class="form-group">
          <label>Prénom</label>
          <%= f.text_field :first_name %>
        </div>
        <div class="form-group">
          <label>Nom</label>
          <%= f.text_field :last_name %>
        </div>
        <div class="form-group">
          <label>Age</label>
          <%= f.text_field :age %>
        </div>
        <div class="form-group">
          <label>Une description de ta personne</label>
          <%= f.text_area :description, class: 'form-control' %>
        </div>
      <!--
        <div class="form-group">
          <label>Ville</label>
          <#%= f.text_field :city_name, class: 'form-control' %>
        </div>
      -->
        <div class="form-group">
          <label>Email</label>
          <%= f.text_field :email %>
        </div>
        <div class="form-group">
          <label>Mot de passe</label>
          <%= f.text_field :password %>
        </div>
        <div class="form-group">
          <label>Confirmation du mot de passe</label>
          <%= f.text_field :password_confirmation %>
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-secondary">Créer ton compte</button>
        </div>
      <% end %>
    </div>
  </div>
</div>
  